# .github/workflows/docker-on-tag.yml
name: Build Docker Image on Tag

on:
  push:
    tags:
      - 'v*'  # triggers on tags like v1.0.0, v2.1.5 etc.

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true  # set to true if you want to push
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}